/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilTorqButton {
        /**
          * The text to show inside the button
         */
        "buttontext": string;
        /**
          * Could be a primary button, a secondary, etc
         */
        "buttontype": string;
    }
}
declare global {
    interface HTMLStencilTorqButtonElement extends Components.StencilTorqButton, HTMLStencilElement {
    }
    var HTMLStencilTorqButtonElement: {
        prototype: HTMLStencilTorqButtonElement;
        new (): HTMLStencilTorqButtonElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-torq-button": HTMLStencilTorqButtonElement;
    }
}
declare namespace LocalJSX {
    interface StencilTorqButton {
        /**
          * The text to show inside the button
         */
        "buttontext"?: string;
        /**
          * Could be a primary button, a secondary, etc
         */
        "buttontype"?: string;
    }
    interface IntrinsicElements {
        "stencil-torq-button": StencilTorqButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-torq-button": LocalJSX.StencilTorqButton & JSXBase.HTMLAttributes<HTMLStencilTorqButtonElement>;
        }
    }
}
